In [1]:
import os
from stl import mesh
import numpy as np

tactip_mesh = mesh.Mesh.from_file('face.stl')

print(tactip_mesh.points)

[[19.745987  15.015604   3.4348643 ... 19.886633  15.015604   3.5791461]
 [19.886633  15.015604   3.5791461 ... 20.024752  24.484396   3.7258468]
 [19.886633  15.015604   3.5791461 ... 20.024752  15.015604   3.7258468]
 ...
 [19.702839  31.11759   10.        ... 18.965101  31.792679  10.       ]
 [18.965101  31.792679  10.        ... 19.006403  31.73317   10.       ]
 [22.115494  27.582209  10.        ... 22.12538   27.587095  10.       ]]


In [ ]:
print(tactip_mesh.points.shape)


(60114, 9)


In [14]:
%matplotlib qt

In [15]:
import numpy as np
import trimesh
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection

def set_axes_equal(ax):
    """Make axes of 3D plot have equal scale."""
    x_limits = ax.get_xlim3d()
    y_limits = ax.get_ylim3d()
    z_limits = ax.get_zlim3d()
    x_range = x_limits[1] - x_limits[0]
    y_range = y_limits[1] - y_limits[0]
    z_range = z_limits[1] - z_limits[0]
    max_range = max(x_range, y_range, z_range) / 2.0

    x_middle = np.mean(x_limits)
    y_middle = np.mean(y_limits)
    z_middle = np.mean(z_limits)

    #ax.set_xlim3d(x_middle - max_range, x_middle + max_range)
    #ax.set_ylim3d(y_middle - max_range, y_middle + max_range)
    #ax.set_zlim3d(z_middle - max_range, z_middle + max_range)
    ax.set_xlim3d(0, 30)
    ax.set_ylim3d(0, 30)
    ax.set_zlim3d(0, 30)

# ---- 실제 시각화 코드 ----
mesh_data = trimesh.load_mesh('face.stl')
triangles = mesh_data.triangles

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.add_collection3d(Poly3DCollection(triangles, linewidths=0.1, alpha=0.5))

all_pts = triangles.reshape(-1,3)
ax.auto_scale_xyz(all_pts[:,0], all_pts[:,1], all_pts[:,2])

set_axes_equal(ax)  # ← 이 한 줄로 축 스케일 통일!

ax.set_xlabel('X')
ax.set_ylabel('Y')
ax.set_zlabel('Z')
plt.show()

In [17]:
import os
os.environ['OPEN3D_DISABLE_WEB_VISUALIZER'] = 'true'
import open3d as o3d

mesh = o3d.io.read_triangle_mesh("face.stl")
o3d.visualization.draw_geometries([mesh])  # 별도 GUI 창이 뜹니다