넘파이는 array 사용할 때

In [28]:
# NumPy에 대해
# NumPy는 다차원 배열을 처리하는 데 필요한 기능을 제공하는 라이브러리이다.
# ndarray 클래스는 다차원 배열을 생성하고 다양한 연산을 수행하는 기능을 제공한다.

In [29]:
import pandas as pd
import numpy as np
import os

In [30]:
a = np.array([[1, 2, 3],[4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
print(a[0])
print(a[0,0])
print(a[0,1])

[1 2 3]
1
2


In [32]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# filepath = os.getcwd()
# filepath

'c:\\Users\\Edward\\Documents\\GitHub\\Portfolio\\School\\DS'

In [ ]:
df = pd.read_csv('C:/Users/Edward/Downloads/titanic.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [37]:
df.loc[0:1, ['Name', 'Age']]

Name   Age
0                            Braund, Mr. Owen Harris  22.0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0